//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIBot_FYP16004.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Channel { get; set; }
        public System.DateTime Time { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
    }
}
