//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIBot_FYP16004.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCatalog
    {
        public string Manufacturer { get; set; }
        public string Name { get; set; }
        public string PriceBand { get; set; }
        public Nullable<double> PriceUSD { get; set; }
        public string DeviceCollection { get; set; }
        public string FormFactor { get; set; }
        public string DeviceCategory { get; set; }
        public string DeviceHeadlineShort { get; set; }
        public string DeviceHeadlineLong { get; set; }
        public string DeviceDescription { get; set; }
        public string GenericDescriptor { get; set; }
        public string DeviceNarrative { get; set; }
        public string Feature1Title { get; set; }
        public string Feature1 { get; set; }
        public string Feature2Title { get; set; }
        public string Feature2 { get; set; }
        public string Feature3Title { get; set; }
        public string Feature3 { get; set; }
        public string Feature4Title { get; set; }
        public string Feature4 { get; set; }
        public string ImageURL { get; set; }
        public int Id { get; set; }
    }
}
